spring:
  application:
    name: Local-chef-fit
  datasource:
    url: jdbc:mysql://localhost:3306/local-chef-fit?useSSL=false
    username: root
    password: Nagina_123
  jpa:
    hibernate:
      #ddl-auto: create-drop # Correct key for table creation
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
