spring:
  application:
    name: Local-chef-fit
  datasource:
    url: jdbc:mysql://localhost:3306/local-chef-fit?useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop # Options: none, validate, update, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
